/** Application-private CBOR map labels for `/api/forest/{log-id}/genesis` (v2). */

export const FOREST_GENESIS_LABEL_GENESIS_VERSION = -68009;
export const FOREST_GENESIS_LABEL_BOOTSTRAP_LOG_ID = -68010;
export const FOREST_GENESIS_LABEL_UNIVOCITY_ADDR = -68011;
export const FOREST_GENESIS_LABEL_CHAIN_ID = -68013;
export const FOREST_GENESIS_LABEL_GENESIS_ALG = -68014;
export const FOREST_GENESIS_LABEL_BOOTSTRAP_KEY = -68015;
export const FOREST_GENESIS_LABEL_UNIVOCITY_VARIANT = -68016;
export const FOREST_GENESIS_LABEL_UNIVOCITY_DEPLOYER = -68017;
export const FOREST_GENESIS_SCHEMA_V2 = 2;
export const FOREST_GENESIS_UNIVOCITY_VARIANT_UUPS_COUNTERFACTUAL =
	'uups-counterfactual' as const;
